#!/usr/bin/env bash
# Fix nginx to run as nginx user and listen on port 8080
sed -i 's/^#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[\:\:\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
pkill -9 -f apache2 || true
sleep 1
service nginx restart
