#!/usr/bin/env bash
# Fix nginx to run as nginx user and listen on port 8080
sed -i 's/^#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[\:\:\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
kill -9 "$(pgrep -f apache2 | tr '\n' ' ')" 2>/dev/null || true
service nginx restart
