#!/usr/bin/env bash
# Fix nginx to run as nginx user and listen on port 8080
sed -i 's/^#user nobody;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/^user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[\:\:\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
service apache2 stop
service nginx restart
