#!/usr/bin/env bash
# Installs and configures HAProxy on lb-01 with round robin algorithm
apt-get update -y
apt-get install haproxy -y

echo "ENABLED=1" >> /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 44.201.255.156:80 check
    server web-02 44.202.105.198:80 check
EOF

service haproxy restart
