#!/usr/bin/env bash
# Configures Nginx with a 301 redirect on /redirect_me

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.html

sed -i 's#server_name _;#server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;#' /etc/nginx/sites-available/default

service nginx restart
